language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-19


    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-15
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-18
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-20
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-15
    - sys-img-x86-android-16
    - sys-img-x86-android-17
    - sys-img-x86-android-18
    - sys-img-x86-android-19
    - sys-img-x86-android-20
    - sys-img-x86-android-21
    - sys-img-x86-android-22

before_install:
    - chmod +x gradlew

    #avoid cache
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/