package cn.edu.dlut.tiyuguan.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.edu.dlut.tiyuguan.bean.RemindBean;
import cn.edu.dlut.tiyuguan.bean.OrderBean;
import cn.edu.dlut.tiyuguan.bean.UserBean;

import cn.edu.dlut.tiyuguan.dao.RemindBeanDao;
import cn.edu.dlut.tiyuguan.dao.OrderBeanDao;
import cn.edu.dlut.tiyuguan.dao.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig remindBeanDaoConfig;
    private final DaoConfig orderBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final RemindBeanDao remindBeanDao;
    private final OrderBeanDao orderBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        remindBeanDaoConfig = daoConfigMap.get(RemindBeanDao.class).clone();
        remindBeanDaoConfig.initIdentityScope(type);

        orderBeanDaoConfig = daoConfigMap.get(OrderBeanDao.class).clone();
        orderBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        remindBeanDao = new RemindBeanDao(remindBeanDaoConfig, this);
        orderBeanDao = new OrderBeanDao(orderBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(RemindBean.class, remindBeanDao);
        registerDao(OrderBean.class, orderBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        remindBeanDaoConfig.getIdentityScope().clear();
        orderBeanDaoConfig.getIdentityScope().clear();
        userBeanDaoConfig.getIdentityScope().clear();
    }

    public RemindBeanDao getRemindBeanDao() {
        return remindBeanDao;
    }

    public OrderBeanDao getOrderBeanDao() {
        return orderBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
